### ISSUE TITLE
Empty actions list

### ISSUE THREAD

**Issue by naamapps** [luckysmg/flutter_swipe_action_cell#11] opened 2020-11-19 15:47 UTC
Hey really nice package! 
I have a little problem,
I want to show actions with a condition. 
My application can be RTL and LTR, I need to set the leading actions if the direction of the app is ltr and trailing actions need to be empty. If the direction of the app is rtl I need to set the trailing actions and the leading actions need to be empty.
However, errors show up if the list of the actions is empty.
I looked at the code, and saw you initialize the actions with `defaultActions` list.
This is fine, but if I over swipe the item, there is a slight red background which is shown (an empty `SwipeAction` I suppose).
Here is a gif to show the issue:
![VideoCrop1605800497478](https://user-images.githubusercontent.com/37176893/99688590-a95b7d00-2a8e-11eb-8778-a65ca2a2b904.gif)

I think you should allow null or an empty actions list.
Or fix the red background of the empty `SwipeAction` in the `defaultActions` list.
Thanks!

**Comment by luckysmg** [comment] 2020-11-19 15:59
Thx for your feedback.Could you get me your demo code so that I can reproduce your problem quickly?



发自我的iPhone


------------------ Original ------------------

**Comment by luckysmg** [comment] 2020-11-19 16:04
I’ll try to reproduce it

**Comment by naamapps** [comment] 2020-11-19 16:12
@luckysmg Sorry but I don't have a demo code. My app is really close to release so I can't really share my code.
Hope you can understand

**Comment by luckysmg** [comment] 2020-11-19 16:17
Ok,I see. I ll try my best to fix it.



发自我的iPhone


------------------ Original ------------------

**Comment by naamapps** [comment] 2020-11-19 16:17
@luckysmg I have found another issue,
If I add a `SwipeActionController` to the `SwipeActionCell` edit mode is activated by default and shows a minus icon with red background.
Is there a way to remove this icon or disable edit mode?

**Comment by luckysmg** [comment] 2020-11-20 00:16
Why?In edit mode we need this icon



发自我的iPhone


------------------ Original ------------------

**Comment by luckysmg** [comment] 2020-11-20 01:01
Need I can't reproduce your first issue.
Here is my test
[gif_image](https://github.com/luckysmg/daill_images/blob/main/IMB_IrMqmG.GIF?raw=true)

And here is my code...


```dart

///your logic
    bool ltr = false;

    List<SwipeAction> actions = [
      SwipeAction(
          title: "delete",
          onTap: (handler) async {
            await handler(true);
            list.removeAt(index);
            setState(() {});
          }),
      SwipeAction(title: "action3", color: Colors.orange, onTap: (handler) {}),
    ];
    return SwipeActionCell(
      controller: controller,
      index: index,
      key: ValueKey(list[index]),
      performsFirstActionWithFullSwipe: true,
      trailingActions: ltr ? defaultActions : actions,
      leadingActions: !ltr ? defaultActions : actions,
      child: Padding(
        padding: const EdgeInsets.all(15.0),
        child: Text("This is index of ${list[index]}",
            style: TextStyle(fontSize: 25)),
      ),
    );

```

**Comment by luckysmg** [comment] 2020-11-20 05:26
I think I have fixed this issue.I have pushed the v1.2.7 to fix the overscroll you mentioned. You can check it.And you can pass the param "trailingActions" or "leadingActions" with null explicitly .

**Comment by luckysmg** [comment] 2020-11-20 05:54
And about your second issue,guard that your cell's backgroundColor param is not Colors.transparent when you pass the controller in.

**Comment by naamapps** [comment] 2020-11-20 08:53
@luckysmg Nicely done!
The overscroll issue is resolved 👍 
About the edit mode icon that appears when adding a controller to the `SwipeActionCell`,
Even if I put a background color to the cell, it's still there.

Maybe only show the icon if the user entered edit mode?
Here is an image that show the problem: 
![20201120_105137](https://user-images.githubusercontent.com/37176893/99779939-7a8ce780-2b1e-11eb-9736-b576b0ec1226.jpg)

As you can see, there is a little red icon next to my custom shaped action.
Thanks!

**Comment by luckysmg** [comment] 2020-11-20 08:57
Ok ,I ll check it

**Comment by luckysmg** [comment] 2020-11-20 09:01
I ll fix it as soon as i Can

**Comment by luckysmg** [comment] 2020-11-20 09:16
I have pushed the version v1.3.0,you can check it again 😀

**Comment by naamapps** [comment] 2020-11-20 09:53
@luckysmg You are the best!
Everything works like a charm.
Thank you

**Comment by luckysmg** [comment] 2020-11-20 10:02
I'll close this issue,If you got any other questions,you can reopen this issue whenever you want.

**Closed** 2020-11-20 10:02 UTC
Labels: beta, bug, bugfix waiting for testing, waiting response
